### ISSUE TITLE
MOBILE: Video banner on homepage is the wrong size

### ISSUE THREAD

**Issue by openhousepictures** [philhancox/openhousepictures#5]
![IMG_3295](https://github.com/philhancox/openhousepictures/assets/144906896/e6e3c674-824d-4992-ba49-d72287cc4dd3)

**Comment by philhancox** [comment]
The video is a background of a "container" which contains the hero text, sub title etc. If there's a lot of content, the container increases in size but the video doesn't - otherwise it would stretch the height of the video which I'm sure we don't want.
As this is mobile, it would be very difficult to get the video the "right size" without removing a lot of the text and then making the text much smaller.
I would recommend that on mobile devices, replacing the background video with a background image and then putting the video in the page itself, underneath the container. The desktop version wouldn't change, just the mobile.
