### ISSUE TITLE
MOBILE: Dead space/text and space formatting issues on different areas of the homepage

### ISSUE THREAD

**Issue by openhousepictures** [philhancox/openhousepictures#8]
![IMG_3306](https://github.com/philhancox/openhousepictures/assets/144906896/6cbdac15-8ad3-4798-8669-d2e3d1861d7f)
![IMG_3304](https://github.com/philhancox/openhousepictures/assets/144906896/2bdd4dc9-c30e-4cd6-a925-037b3372bad4)
![IMG_3305](https://github.com/philhancox/openhousepictures/assets/144906896/1676cdce-1380-43d9-ab30-e2ac0af4464d)

**Comment by openhousepictures** [comment]
![IMG_3298](https://github.com/philhancox/openhousepictures/assets/144906896/ff9a2b64-4c89-4447-9734-0720b0e7cfdc)
![IMG_3297](https://github.com/philhancox/openhousepictures/assets/144906896/275df16e-fc2a-4f01-8fc2-105c94919587)
![IMG_3296](https://github.com/philhancox/openhousepictures/assets/144906896/a697ba05-1689-418b-b4e4-b4e1b822d854)

**Comment by philhancox** [comment]
I've cleaned up some of the more obvious spacing issues, and the squashed button tabs. 
Anything else might require more direction, particularly the logos which are uploaded in specific dimensions with suitable white space to look consistent on things like the slider and it might be the image that's the problem here. Things like the background colour and positioning, maybe centrally, only on mobile design could help, Brad can assist in discussing mobile specific design visions.
